apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: kiali
  namespace: istio-system
spec:
  prefix: /kiali/
  rewrite: ""
  service: kiali:20001
  bypass_auth: true
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: jaeger
  namespace: istio-system
spec:
  prefix: /jaeger/
  rewrite: ""
  service: tracing
  bypass_auth: true
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: frontend
  namespace: default
spec:
  prefix: /
  service: frontend
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: jaeger-query
  namespace: istio-system
spec:
  grpc: True
  prefix: /jaeger.api_v2.QueryService/
  rewrite: /jaeger.api_v2.QueryService/
  service: jaeger-query:16686
