apiVersion: getambassador.io/v2
kind: AuthService
metadata:
  name: authentication
spec:
  auth_service: "authservice:3000"
  allowed_request_headers:
    - "x-qotm-session"
  allowed_authorization_headers:
    - "x-qotm-session"
