apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: productcatalogservice
  namespace: default
spec:
  hosts:
  - productcatalogservice
  http:
  - fault:
      abort:
        httpStatus: 500
        percentage:
          value: 100
    route:
    - destination:
        host: productcatalogservice
  - route:
    - destination:
        host: productcatalogservice
