apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: productcatalogservice
  namespace: default
spec:
  hosts:
    - productcatalogservice
  http:
    - route:
        - destination:
            host: productcatalogservice
      match:
        - uri:
            prefix: /
          ignoreUriCase: true
      fault:
        abort:
          percentage:
            value: 100.0
          httpStatus: 500
    - route:
        - destination:
            host: productcatalogservice
