apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: testservice
  namespace: default
spec:
  hosts:
  - testservice
  http:
  - route:
    - destination:
        host: testservice
    fault:
      abort:
        httpStatus: 500
        percentage:
          value: 100
  - route:
    - destination:
        host: testservice
